# Generated by Django 5.0.7 on 2024-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_tag_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="event_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
